[package]
name = "make-public-structfield-without-punctuated-exercise"
version = "0.1.0"
edition = "2021"

[dependencies]
make-public-structfield-without-punctuated-exercise-macro = { path = "./make-public-macro" }
