[package]
name = "panic-to-result-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.69"
quote = "1.0.33"
syn = { version = "2.0.39", features = ["full", "extra-traits"]}

[lib]
proc-macro = true
