[package]
name = "iac-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.33"
syn = { version = "2.0.39", features = ["extra-traits"]}
edit-distance = "2.1.0"

[lib]
proc-macro = true
